### ISSUE TITLE
Clarification on RAW/TXTH?

### ISSUE THREAD

**Issue by IngwiePhoenix** [TGEnigma/p4gpc.modloader#1]
I just completed my initial playthrough of P4G and thought it'd be an interesting spin on things if I started replacing things in the game for NG+ - and one of them, would be the music.

From what I understand, I'd be using a WAV (PCM) file for `.raw`. But, what exactly are the options within those? I can see what bitrate and channels would be for - but what about the others? Is there a tool that would allow me to convert existing files into the apropriate format, or another that would just allow me to extract the required information off an existing file?

I have only done the pure basics of sound design and engeneering - mainly because a friend of mine bombarded me with details for a long, long time. So aside from the differences in filetypes and their capabilities, I still lack a little bit of knowledge...

**Comment by NerduMiner** [comment]
The readme links to a tool where you can convert .wav files into the proper RAW format along with creating a TXTH file that you place alongside the RAW in your mods folder.

**Comment by IngwiePhoenix** [comment]
Awesome, thanks! I must've overlooked that when I read that first.

In order to prepare my project, I would have to extract the original `.xsb`/`.xwb` combo to get ahold of the indices I'd need to replace. Do you know of a method to extract that? `unxwb` works, but doesn't seem to handle XSBs all too well (as noted by, what I assume is, the developer here: https://zenhax.com/viewtopic.php?t=6910#p29761 )

**Comment by tge-was-taken** [comment]
Using the vgmstream plugin for foobar2000 you can load the xwb as a playlist and it will also load the cue names from the associated xsb.
