### ISSUE TITLE
Launching Reloaded II with Show Console Error

### ISSUE THREAD

**Issue by T-PoseRatkechi** [TGEnigma/p4gpc.modloader#2]
Failed to Load Reloaded-II
The parameter is incorrect.
  at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
  at System.Console.set_OutputEncoding(Encoding value)
at modloader.P4GPCModLoader...ctor(ILogger logger, Config configuration, IReloadedHooks hooks) in
C:\p4gpc.modloader\modloader\P4GPCModLoader.cs:line 36
...
P4G still opens, but anything in the mods folder isn't loaded. Reloaded times out and exits. Disabling the console seems to fix it and mods in the folder are loaded.

Also, noticed that save files not created when the game is loaded through Reloaded disappear from the load menu. Starting the game through Steam doesn't fix any of the missing saves, whether saved with or without the ModLoader. The only files edited were save slot 1 (data0001.bin/data0001.binslot) and system.bin.

**Comment by tge-was-taken** [comment]
Is this with the latest version?

**Comment by T-PoseRatkechi** [comment]
The non-beta P4G, latest ReloadedII, and ModLoader v1.1.1. Tried ModLoader v1.1.0 and had the same error. Switching between ModLoader versions also hides saves made with the other.

**Comment by tge-was-taken** [comment]
Try this build: https://ci.appveyor.com/api/buildjobs/ua9vi76e1uuy1iat/artifacts/build%2Frelease.zip
Should be fixed.

**Comment by T-PoseRatkechi** [comment]
It is! Huge thanks!
